### ISSUE TITLE
[RFC] @talend/design-system as dependency

### ISSUE THREAD

**Issue by frassinier** [Talend/ui#3518]
## Status

In progress

## Context
The package `@talend/design-system` has the mission of being our centralized shared UI library.
It delivers more and more design decisions helping us build systemic UI through documented components.
It becomes a standalone dependency with its own lifecycle using [changesets](https://github.com/atlassian/changesets).

## Problems

Today, the design-system is a dependency of Talend/ui.

Its components are not being used directly but through a Talend/UI proxy.

Some of them are also heavily intertwined with Talend/UI components, blurring the line between each dependency's purposes and lifecycles. (ie: the design system's `<ThemeProvider />` is baked into Talend/UI's `Layout`).

It has the benefit of bringing some design system enhancements and features "for free" to Talend/UI consumers, but it also locks them into a single version of both libraries.

We need to change that, we need to let the consumers choose which version they want to use and to make dependencies (and their roles) more explicit.

## Solutions

We want the front-end team to commit to the following missions:

1. Remove that Design System usage into `Layout` and other Talend/UI components when Talend/UI only serves as a proxy.
2. Use `@talend/design-system` in the Talend products as an explicit dependency instead.
3. Use  `ThemeProvider` and other available DS assets (`Button`, `Accordion` etc...) directly in the Talend products.
4. Progressively depreciate and migrate UI elements from Talend/UI into the design system

**Comment by jmfrancois** [comment]
> it also locks them into a single version of both libraries.

In fact that is a wrong. `@talend/react-components` require a minimal version of the DS. So the project can require an higher version of the Design system and so choose which version to use but higher than the one required. As usual with dependencies.

> 1. Remove that Design System usage into Layout and other Talend/UI components when Talend/UI only serves as a proxy

Ok but note this is a first breaking change in TUI to handle. But ok for it, it makes sens.

> 2. Use @talend/design-system in the Talend products as an explicit dependency instead.

You can already do this. I don't get the point.

> 3. Use ThemeProvider and other available DS assets (Button, Accordion etc...) directly in the Talend products.

Yes this is part of the breaking change in 1.

> 4. Progressively depreciate and migrate UI elements from Talend/UI into the design system

This is the discussion about the migration I would like to talk about.

## Migration

We have to do a strong choice here and it will impact the next years for us. The proposal for the migration is not clear to me.
We have worked during years without breaking changes to make the life easier in projects. We follow semver and will continue to follow semver. But we clearly need to modernize our components

Lets go back to the target

- rewrite using Typescript
- use more modern approach to style
- work with UX
- documentation/spec driven
- use token based styling to support white labeling

And for sure we will keep a high level of quality (test coverage) and justify every breaking changes.

But now we have @talend/react-components and @talend/design-system and a rapid overview show most of components from the DS are just not used today.

Migrate every components from react-components to the design-system package is a huge work. What is the value we will have back from it ? I mean we need to improve existing component and that is ok. But we have so many components libraries.

At the begining I was agree to create the DS to replace bootstrap, work with UX and iterate over react-components to make it great again and keep it's black box approach to avoid the need of custom CSS in projects.

Here we have replaced this by let's write yet another component library as a kind of bootstrap and it costs a lot without direct value for our customer. And good luck for migration because we are switching in terms of paradigm.

So I would like to understand why a component can not be re-written in Typescript, re-design to fit a new UX within the same package.
I see most of components will exists in double (triple for those who are already in double) and it will be a mess to know which one to use in the end without having too much technical debt.

It is exactly like OpenSource. You cover a need and give a name to that. Would you like a different name for the next coming major release ?

## Conclusion

So the real choice behind this issue are between

1. Use design-system as react-bootstrap replacement and keep react-components to use the major releases approach to make it great again ? For sure use it as we were using react-bootstrap directly in project. And be sure every components from the DS are also used in react-components (this is not the case today)

2. Do we live with every components in doubles until every projects has migrated all imports from design-systems and removed all from react-components ? Do you think that is realistic ? 

So my answer is: I want a library to replace react-bootstrap and I want to modernize react-components. I see no added value to migrate all components from the react-components to the design-system.

**Comment by Benrajalu** [comment]
Thanks, good questions!

> Use @talend/design-system in the Talend products as an explicit dependency instead.
> > You can already do this. I don't get the point. 

Yeah, some teams do this already, but many don't. We can't fault them, the messaging is unclear, and your comment illustrates it perfectly: when should people use `react-components` vs when should they use `design-system`? What's the difference?

We want to make it simpler. We want a single package for every stateless shared component needs. That implies depreciating and eventually retiring, with no ill will, `react-components`. Which segues into the rest of your comment: "why migrate `react-component` into `design-system`?" 

> Migrate every components from react-components to the design-system package is a huge work. What is the value we will have back from it ? I mean we need to improve existing component and that is ok. But we have so many components libraries.

It is ambitious work. We're aware. The value is the one you've outlined above: 

```
- rewrite using Typescript
- use more modern approach to style
- work with UX
- documentation/spec driven
- use token based styling to support white labeling
```

We no longer want to have "so many components library", eventually we want a single source of truth for UI elements. Our proposal is for that single source to be `design-system`. Which links to this part of your reasoning:

> So I would like to understand why a component can not be re-written in Typescript, re-design to fit a new UX within the same package.

It potentially could. However, we believe that moving things from one package to the other during that process will help the engineering team in two ways: 

1. It's OK to break things. I know this is an unpopular opinion when discussing shared libraries in production, but it's a necessary part of progress. `react-components` has years of experience behind it, and its consumers (and contributors) have learnt a lot in the meantime. Needs have changed, habits as well. We believe it'll be easier to create the "breaking change" versions (if needed!) of existing components in the new package. It's freeing (no need to create clunky layers between the new and the old) and it creates an explicit migration path for current consumers. 

2. It's easier to document what's left to be done. Identifying `react-components` as a legacy library enables us to progressively identify and migrate, component by component. If we merged `design-system` into `react-component` (which I'm aware you're not actually suggesting) we lose that ability, and consumers have no way to know whether they're using a "legacy" component or not. It's part of the issue today: some TUI components are only proxies for the `design-system` package, which makes it hard to document what's what.

> Here we have replaced this by let's write yet another component library as a kind of bootstrap and it costs a lot without direct value for our customer. And good luck for migration because we are switching in terms of paradigm.

That's kind of true, but it's not "kind of bootstrap". The goal of the `design-system` library is to remove the need for bootstrap AND deliver components (atoms but not just that) AND document their guidelines AND provide a 1:1 designers-to-developer "building bricks" experience. 

We also want to remove the "this is a bootstrap" mindset from our shared library. Bootstrap is meant to be overridden, whereas shared component libraries that are part of a company's design system are not. They are element of a specified design language, they are opinionated and work as a "contract" between designers and developers.

That's the value for customers (unified UX, homogenised UI). But it does have a cost. 

> Do we live with every components in doubles until every projects has migrated all imports from design-systems and removed all from react-components ? Do you think that is realistic ?

Yes. Yes we may live with unmigrated components for a while. Yes we think it's realistic, as long as consumers are on board for this. But more importantly, we think it's necessary and dev feedback seems to go that way as well.

**Comment by Benrajalu** [comment]
We had a discussion with the arch team. 

## On depreciating `react-components` 

We don't plan on depreciating the library as a whole in one swift move. That would be folly. We will move in batches. 

The idea is to assess which components are needed at Talend from a systemic standpoint. Some components might move from `react-component` to `design-system` virtually untouched (there will be some TS touching) and some others may not move at all nor be replaced. The point is to rationalise our UI in code and in Figma with a 1:1 toolset and strong documentation.

This will take time and we'll do it in batches. Expect to have `react-components` and `design-system` dependancies both at the same time for a little while (aka "in the long run". This is a marathon, not a sprint).

## On migrating 

How long are we talking about? Well, it depends. 

You are all free to jump to `design-system` already. You will of course be free to migrate your `react-component` dependancies to the provided equivalents in `design-system` in your own time. That's the quick-but-disorganised path. It's a good way for your team to tackle its debt little by little. 

However, we will also need to plan company-wide efforts. Again, working with batches of components, we will need to promote migrations efforts into the Product Rolling Roadmap (PRR). Through there, migration efforts can be undertaken through each product squad's time and must be completed before a set deadline. When that deadline comes, the previous `react-components` components will be removed from the library.

We don't expect to be done overnight and you, consumers and contributors of the library, are the driving factor when it comes to how long this will take.

## On supporting `react-components` 

We're aware that this process will take a lot of time. We think it's worth it, but more importantly, as a Design System team, *we don't really have a choice*. That single source of UI truth is key to providing a consistent user experience across all our products, something the overall solution sorely needs.

Because we can't do it with a big bang, we'll have to "put" the design system into `react-components`. Not as a proxy where calling on `import { Button } from '~@talend/ui/react-components'` actually delivers `import { Button } from '~@talend/ui/design-system'`, but every button inside `react-component` should be using the design system's `Button`. 

With each depreciation wave that the PRR brings, more and more components will disappear from `react-components` in favour of a `design-system` alternative, but we still need to elegantly deal with what will be left.

## On breaking changes

Yes, there will be some. We do plan on keeping closed APIs for our publicly exposed components (another ADR is coming your way to discuss that subject), but as you are all aware, some `react-components` stuff has grown in sometimes chaotic ways. This is a chance to change this, and that will lead to (positive) breaking changes. 

We're also doing this to rationalise our UIs from a design and experience standpoint. Designers will need to vouch that in order to perform such and such actions, then such and such components are expected to be used. That high level of definition and documentation will lead to some components being revised or simply dropped. That of course is also a breaking change for your products, since it can be an evolution of the expected feature-set.

These two reasons for breaking changes don't necessarily stem from the move from one library to another though. They are clearly motivated by the pursuit of a more efficient, more documented and homogenised way to build our UIs.
