### ISSUE TITLE
dynamic-cdn-webpack-plugin compatibility with tsconfig "paths"

### ISSUE THREAD

**Issue by Triazic** [Talend/ui#4217]
**Is your feature request related to a problem? Please describe.**
My project uses tsconfig "paths" feature. When using this package, all of those paths get picked up as external packages and throw spammy errors in the build logs:   
![image](https://user-images.githubusercontent.com/38064196/178893054-da7c684d-19c1-4738-977e-c8fe29d923a5.png)
The 'exclude' feature doesn't seem to work for this purpose. I've tried eg. "@state/*", "@state/", "@state"

My tsconfig:  
 ![image](https://user-images.githubusercontent.com/38064196/178893274-2c13afb2-9dda-4243-badc-f2ce7ad62a5a.png)

**Describe the solution you'd like**
Option 1 - ability to disable those particular error messages
Option 2 - automatic support for tsconfig paths
Option 3 - chained support with  tsconfig-paths-webpack-plugin
Option 4 - exclude feature supporting wildcards
??

**Comment by Triazic** [comment]
I could create a custom resolver that ignores those paths and falls back to @talend/module-to-cdn, I suppose

**Comment by jmfrancois** [comment]
interesting issue indeed.
As you can see [here](https://github.com/Talend/ui/blob/master/fork/dynamic-cdn-webpack-plugin/src/index.js#L284) module exclusion is evaluated this way
```javascript
		const isModuleExcluded =
			this.exclude.includes(modulePath) ||
			(this.only && !this.only.includes(modulePath)) ||
			modulePath.startsWith('@types/');```
			
I do not think custom resolver will help because it happens after this code.
So I would tend to think you should add excludeScope so you could pass the config from your PATH.

At webpack level we do not have access to TS configuration, the code has already been parsed.

**Comment by jmfrancois** [comment]
do not hesitate to re-open if you want to contribute and propose a fix on our side.
I close it as stale.
